# 특정 세대의 대장균 찾기
# 3게대 대장균을 찾아라

SELECT THRD_GEN.ID
FROM ECOLI_DATA THRD_GEN
JOIN (
    SELECT SCND_GEN.ID
    FROM ECOLI_DATA SCND_GEN
    JOIN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    ) FST_GEN
    ON SCND_GEN.PARENT_ID = FST_GEN.ID
) SCND_GEN
ON THRD_GEN.PARENT_ID = SCND_GEN.ID
ORDER BY THRD_GEN.ID