# 더이상 업그레이드할 수 없는 아이템

# PARENT > ITEM_ID로 합치면 > 다음 업그레이드 가능 여부가 나옴

SELECT 
    A.ITEM_ID,
    A.ITEM_NAME,
    A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY A.ITEM_ID DESC
