# 대장균은 일정 주기 분화
# 개체의 자식 수를 출력하는 SQL

SELECT
    A.ID,
    IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT 
        PARENT_ID, 
        COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) B
ON A.ID = B.PARENT_ID
ORDER BY A.ID