-- 코드를 입력하세요
SELECT
    SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM (
    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
    GROUP BY SALES_DATE, USER_ID, PRODUCT_ID
    UNION
    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY SALES_DATE, PRODUCT_ID
) S
WHERE S.SALES_DATE >= '2022-03-01' AND S.SALES_DATE < '2022-04-01'
ORDER BY S.SALES_DATE, S.PRODUCT_ID, S.USER_ID
