# 음식 종류별로 Group
# 즐겨찾기 중 MAX

SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM REST_INFO A
JOIN (
    SELECT 
        FOOD_TYPE, 
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) B
ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.MAX_FAVORITES
ORDER BY A.FOOD_TYPE DESC