# 회원정보
# 판매정보

# 년, 월, 성별별로 집계 > group

SELECT
    YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    A.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE B
JOIN USER_INFO A
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER