# 동물보호소 IN
# 동물보호소 OUT
# 데이터유실, 입양은 있고, 들어온 기록이 없는 조회

SELECT
    B.ANIMAL_ID,
    B.NAME
FROM ANIMAL_OUTS B
LEFT JOIN ANIMAL_INS A
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID