# 물고기 정보

#  종류별 이름과 잡은 수
# 종료별 그루핑

SELECT
    COUNT(*) AS FISH_COUNT,
    B.FISH_NAME
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME
ORDER BY FISH_COUNT DESC