
SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / U.TOTAL_COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN (
    SELECT 
        *, 
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
) U
ON S.USER_ID = U.USER_ID
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)