WITH RECURSIVE ECOLI AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT
        E.ID,
        E.PARENT_ID,
        C.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI C
      ON E.PARENT_ID = C.ID
)

SELECT
    COUNT(*) AS COUNT,
    E.GENERATION
FROM ECOLI E
LEFT JOIN ECOLI_DATA C
  ON E.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY E.GENERATION
ORDER BY E.GENERATION;