# 대장균의 분화

# 각 분기별 분화된 개체의 총 수
# CASE WHEN > COUNT

SELECT
    CASE 
        WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q' # 1~3
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q' # 4~6
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q' # 7~9
        ELSE '4Q' # 10~12
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 
    CASE 
        WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q' # 1~3
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q' # 4~6
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q' # 7~9
        ELSE '4Q' # 10~12
    END
ORDER BY QUARTER
    