WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1
    FROM HOURS
    WHERE H < 23
)
SELECT
    H.H AS HOUR,
    COUNT(A.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON H.H = HOUR(A.DATETIME)
GROUP BY H.H
ORDER BY H.H;