# SELECT
#     DISTINCT D.ID,
#     D.EMAIL,
#     D.FIRST_NAME,
#     D.LAST_NAME
# FROM DEVELOPERS D
# JOIN SKILLCODES S
# ON (D.SKILL_CODE & S.CODE) != 0
# WHERE S.CATEGORY = 'Front End'
# ORDER BY D.ID

SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES S
    WHERE S.CATEGORY = 'Front End'
      AND (D.SKILL_CODE & S.CODE) != 0
)
ORDER BY D.ID;