SELECT
    A.EMP_NO,
    A.EMP_NAME,
    CASE 
        WHEN C.SCORE >= 96 THEN 'S'
        WHEN C.SCORE >= 90 THEN 'A'
        WHEN C.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN C.SCORE >= 96 THEN A.SAL * 0.2
        WHEN C.SCORE >= 90 THEN A.SAL * 0.15
        WHEN C.SCORE >= 80 THEN A.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES A
JOIN (
    SELECT 
        EMP_NO,
        AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) C 
ON A.EMP_NO = C.EMP_NO
ORDER BY A.EMP_NO