# 고객 정보
# 식당 리뷰

# 리뷰를 가장 많이 작성한 회원
# 가장 많이 max 작성한 > 이름, 리뷰, 작성일

# SELECT 
#     A.MEMBER_NAME,
#     B.REVIEW_TEXT,
#     DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE A
# JOIN (
#     SELECT
#         MEMBER_ID,
#         REVIEW_TEXT,
#         REVIEW_DATE,
#         COUNT(*) OVER(PARTITION BY MEMBER_ID) AS REVIEW_COUNT
#     FROM REST_REVIEW
#     ORDER BY REVIEW_COUNT DESC
# ) B
# ON A.MEMBER_ID = B.MEMBER_ID
# ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT


SELECT
    C.MEMBER_NAME,
    D.REVIEW_TEXT,
    DATE_FORMAT(D.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT
        MEMBER_ID,
        DENSE_RANK() OVER (ORDER BY REVIEW_COUNT DESC) AS RANKING
    FROM (
        SELECT 
            DISTINCT MEMBER_ID, 
            COUNT(*) OVER(PARTITION BY MEMBER_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
    ) A
) B
JOIN MEMBER_PROFILE C
    ON B.MEMBER_ID = C.MEMBER_ID
JOIN REST_REVIEW D
    ON C.MEMBER_ID = D.MEMBER_ID
WHERE B.RANKING = 1
ORDER BY REVIEW_DATE, D.REVIEW_TEXT
