# 자동차의 대여정보

# 대여시작일 2022-08 ~ 2022-05 대여 5회이상 자동차
# > 월별 대여횟수

# WHERE에서 거르고
# GROUP > CAR_ID, MONTH로 합치고 COUNT

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM (
    SELECT 
        *, 
        COUNT(*) OVER (PARTITION BY CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE >= '2022-08-01' 
        AND START_DATE < '2022-11-01'
) HISTORY
WHERE RECORDS >= 5
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, CAR_ID DESC


