-- 코드를 작성해주세요

SELECT
    DISTINCT ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) S
ON (D.SKILL_CODE & S.CODE) != 0
ORDER BY ID