# 자동차 정보
# 대여 기록 정보

# 자동차 종료 = 세단
# 10월 대여 시작
# 중복 없이, 내림차순

SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE 
    A.CAR_TYPE = '세단'
    AND B.START_DATE >= '2022-10-01'
    AND B.START_DATE < '2022-11-01'
ORDER BY A.CAR_ID DESC