-- 코드를 작성해주세요

SELECT
    SCORE,
    EMP_NO, 
    EMP_NAME, 
    POSITION, 
    EMAIL
FROM (
    SELECT 
        SUM(G.SCORE) AS SCORE,
        E.EMP_NO, 
        E.EMP_NAME, 
        E.POSITION, 
        E.EMAIL,
        DENSE_RANK() OVER (ORDER BY SUM(G.SCORE) DESC) AS rnk
    FROM HR_EMPLOYEES E
    JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
    WHERE G.YEAR = '2022'
    GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
) E
WHERE E.rnk = 1