# 중고거래 게시판

# 2022년 10월 5일 등록
# STATUS > 단어 변환 switch

SELECT
    BOARD_ID,
    WRITER_ID,
    TITLE,
    PRICE,
    CASE STATUS
        WHEN 'SALE' THEN '판매중'
        WHEN 'RESERVED' THEN '예약중'
        ELSE '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE >= '2022-10-05' AND CREATED_DATE < '2022-10-06'
ORDER BY BOARD_ID DESC
