-- 코드를 작성해주세요

SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(F.LENGTH) AS MAX_LENGTH,
    F.FISH_TYPE
FROM FISH_INFO F
JOIN (
    SELECT 
        FISH_TYPE, 
        AVG(IFNULL(LENGTH, 10)) as AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) A
ON F.FISH_TYPE = A.FISH_TYPE
WHERE A.AVG_LENGTH >= 33
GROUP BY F.FISH_TYPE
ORDER BY F.FISH_TYPE